### PR TITLE
Setup and document local development

### LINKED ISSUE #13: Table of contents is not in the correct order
The proper order should be:
- Getting Started
- Introduction
- Specification Explained
- Best Practices

### LINKED ISSUE #14: The Home page should be removed
It is based on the README file which was only a placeholder. This page should be removed and the new landing page should be the Getting Started one.

The big logo and the note regarding the site's theme are nice, though, so maybe they can be merged into Getting Started.

### LINKED ISSUE #15: The OpenAPI Specification Explained page has two Table of Contents
I guess because `has_children == true` a TOC is automatically added by the theme, but it already has one, and it's more detailed. The automatic TOC should be removed.

### LINKED ISSUE #17: Licensing of the documentation
According to the OpenAPI project charter, section 7.3 , the documentation, by default, should be released under Creative Commons Attribution 4.0 International License. https://www.openapis.org/participate/how-to-contribute/governance

### PR DESCRIPTION
**Pull request by philsturgeon**
Trying to fix a few things like Home showing up with no real content and strange ordering for docs, I noticed there was already a PR that had conflicts. I figured I'd give it a refresh and noticed there was no Gemfile, no way to run this locally. I don't want anyone having to push to prod to see how things work, so lets document the process and see the contributions come flooding in!

Replaces https://github.com/OAI/Documentation/pull/18

- Fixes conflicts
- Instead of deleting README.me we can exclude it from Jekyll.

Closes #13
Closes #14
Closes #15
Closes #17

### TODO

* [x] add Docker config so local Ruby doesn't get munged

### CODE REVIEW

**Comment by philsturgeon** [comment]
@darrelmiller I noticed you approved #18 but it never got merged. If you approve this could you merge it, or could you point me at the person with the power?

**Comment by kevinswiber** [comment]
@philsturgeon Looking pretty good!

Images aren't showing up locally.  For example, only line 89 of `specification/structure.md`, it references `data="img/openapi-object.svg"`.  This could be changed to `data="{{site.baseurl}}/img/openapi-object.svg"`.  Looks like there are a few files that would be impacted.

```
grep -rn \"img specification
specification/parameters.md:15:  <object type="image/svg+xml" data="img/parameter-object.svg"></object>
specification/structure.md:89:  <object type="image/svg+xml" data="img/openapi-object.svg"></object>
specification/content.md:17:  <object type="image/svg+xml" data="img/content-field.svg"></object>
specification/components.md:18:   <object type="image/svg+xml" data="img/components-object.svg"></object>
specification/paths.md:17:  <object type="image/svg+xml" data="img/paths-object.svg"></object>
specification/servers.md:17:  <object type="image/svg+xml" data="img/server-object.svg"></object>
```

Other than that, it might be good to add some info in the README on how to run it locally.

**Comment by segfaultxavi** [comment]
Also, I would like to bring to your attention that the images contain links, i.e. they contain clickable areas (both in the SVG and the source DOT files).

For example:
https://github.com/OAI/Documentation/blob/main/img/components-object.dot#L7

**Comment by philsturgeon** [comment]
@segfaultxavi thankfully those files are linking to `https://spec.openapis.org/*` not the specificaiton pages in this documentation.

@kevinswiber fixed those links, thanks for catching that!

**Review by MikeRalphson — APPROVED** [review]
LGTM - tested locally

**Pull request merged**
