### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ncaidin**
We are going to publish in conjunction with the 3.1.0 release. I think we should get rid of the "Work in progress" message. Agreed?

### CODE REVIEW

**Comment by segfaultxavi** [comment]
Agreed!

**Review by segfaultxavi — APPROVED** [review]

**Comment by MikeRalphson** [comment]
The examples still seem to reference version `3.0.3` - is this correct, there was some talk of changes for `3.1.0` - or are we still targetting the 'supported by tools' version rather than the latest?

**Comment by ncaidin** [comment]
I believe @miqui reviewed the documentation to confirm it is compatible with 3.1. Can you please create another pull request to update it to say 3.1 @MikeRalphson ?

**Comment by MikeRalphson** [comment]
@ncaidin I can do if that's what's wanted. The links to the spec itself will also need to be updated, but the 'pretty' rendered version of version 3.1.0 doesn't exist yet (i.e. until the release PR is merged into `master` and we run the rendering utility).

**Comment by ncaidin** [comment]
Good point @MikeRalphson . Let's wait for the pretty rendered version of the Spec.

**Comment by MikeRalphson** [comment]
@ncaidin no problem - I'll be generating it as soon as possible after the release PR is merged. In the meantime I've just raised PR #21 for a small fix to the minimal OpenAPI example.

**Pull request merged**
